# The language of the webpage
lang: zh-CN

# Change to your timezone
timezone: Asia/Shanghai

title: luckystar space

url: "https://starfading.github.io"
baseurl: ""

github:
  luckystar: songxingchen

social:
  name: songxingchen
  email: starfading7@gmail.com
  links:
    - https://github.com/starfading

theme_mode: light
# light / dark / dual

avatar: /assets/images/avatar.jpg

toc: true

comments:
  provider:
  # provider: giscus

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

kramdown:
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true

collections:
  tabs:
    output: true
    sort_by: order

sass:
  style: compressed

